image: alpine/latest
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~rasch/fraktur
environment:
  project: fraktur
secrets:
  - 6845da96-bf4e-4eed-81e4-35f0c5541d63 # NPM publish token
tasks:
  - test: |
      cd "$project"
      npm test
  - stop_if_not_release: |
      cd "$project"
      git describe --exact-match HEAD || complete-build
  - release: |
      cd "$project"
      echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      set +x
      . ~/.env
      set -x
      npm publish --access public
